### ISSUE TITLE
Failure to parse DAT file with Ruby 1.9.1

### ISSUE THREAD

**Issue by zohararad** [pauldix/domainatrix#5]
When using Domainatrix with Ruby 1.9.1 (p378 on OSX 10.6 i386) the following error occurs when calling Domainatrix.parse:
ArgumentError: invalid byte sequence in US-ASCII
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:14:in `strip'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:14:in`block in read_dat_file'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:13:in `each'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:13:in`read_dat_file'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:9:in `initialize'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix.rb:11:in`new'
        from /opt/lib/ruby/gems/1.9.1/gems/domainatrix-0.0.7/lib/domainatrix.rb:11:in `parse'
        from (irb):3
        from /opt/bin/irb:12:in`<main>'

FIX:

change domainatrix/domain_parser.rb:14 from:
line = line.strip

to: line = line.force_encoding('utf-8').strip

**Comment by pauldix** [comment]
works with 1.9.2 now
