### ISSUE TITLE
Exception on IP address in host string

### ISSUE THREAD

**Issue by igrigorik** [pauldix/domainatrix#6]
<pre>
ruby-1.9.2-p0 > Domainatrix.parse('http://74.205.88.194/article/news/microsoft_ballmer_envious_ipads_success_insists_windows_tablets_are_priority')
NoMethodError: undefined method `has_key?' for nil:NilClass
    from /Users/igrigorik/.rvm/gems/ruby-1.9.2-p0/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:52:in `block in parse_domains_from_host'
    from /Users/igrigorik/.rvm/gems/ruby-1.9.2-p0/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:47:in `each_index'
    from /Users/igrigorik/.rvm/gems/ruby-1.9.2-p0/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:47:in `parse_domains_from_host'
    from /Users/igrigorik/.rvm/gems/ruby-1.9.2-p0/gems/domainatrix-0.0.7/lib/domainatrix/domain_parser.rb:33:in `parse'
    from /Users/igrigorik/.rvm/gems/ruby-1.9.2-p0/gems/domainatrix-0.0.7/lib/domainatrix.rb:12:in `parse'
    from (irb):2
    from /Users/igrigorik/.rvm/rubies/ruby-1.9.2-p0/bin/irb:17:in `<main>'
ruby-1.9.2-p0 > 
</pre>

**Comment by ryana** [comment]
Was there ever any discussion about this ticket?

**Comment by igrigorik** [comment]
Don't think so :)

**Comment by vinnyglennon** [comment]
Same problem on Domainatrix.parse("http://91.205.157.40") . Seems all ip addresses are an issue.

**Comment by derekorgan** [comment]
Would be nice if you could add some flag that checks if host is actually an IP. E.g  @is_ip_address = true
